// Mock data for the Honda AMS web demo — SLM Resolver (L1 triage → L2/L3 renovation).
// Everything here is mock/hard-coded so the demo flow runs smoothly; swap in the real SLM later.
// RFP PM2.0 mapping: L2 = fix by operation (Common L2 Services, p.78-79);
// L3 = code fix / renovation (Common L3 Services p.80 + Zero Dev p.84).

export type Layer = "l2" | "l3" | "route";

export interface Customer {
  ini: string;
  name: string;
  loc: string;
  email: string;
  phone: string;
  veh: string; // may contain <b>
  vin: string; // may contain <b class='ok'>
}

export interface Step {
  k: string;
  kk: string;
  v: string; // allows <span class='hl|cy'>
  ev?: string[]; // evidence, allows <span class='g|r|a|c|f'>
  real?: boolean; // evidence generated by the real SLM (SLM badge)
}

/** RCA generated by the SLM at L1 (real) — carried into the resolver for display. */
export interface SlmRca {
  evidence: string[];
  summary: string;
  nextActions: string[];
  owner?: string | null;
  escalation?: string | null;
  affectedSystem?: string | null;
  similarIncident?: string | null;
  missing?: string[];
}

export interface DiffLine {
  t: "cmt" | "add" | "del";
  x: string;
}
export interface ExecLine {
  t: "cmd" | "out" | "ok";
  x: string;
}
export interface RouteInfo {
  rc: string;
  to: string; // allows <b>
  chips: { t: string; ok?: boolean }[];
}

export type Status = "queued" | "processing" | "resolved";

export interface Ticket {
  id: string;
  sev: "2" | "3";
  sys: string;
  impact: string;
  title: string;
  complaint: string;
  customer: Customer;
  layer: Layer;
  rc: string;
  rb: string;
  conf: number;
  mttr: string;
  steps: Step[];
  diff?: DiffLine[];
  testName?: string;
  reEval?: string;
  exec?: ExecLine[];
  route?: RouteInfo;
  slm?: SlmRca; // real RCA (if the ticket came from L1 via the SLM)
  status: Status;
}

const T4471: Omit<Ticket, "status"> = {
  id: "INC-4471",
  sev: "2",
  sys: "26GTC · Eligibility · SSP",
  impact: "~1,412 vehicles · US-West",
  title: "Paid for Touring but the app still asks to Subscribe — Remote Climate/Start locked",
  complaint:
    "I paid for the Touring plan on my CR-V and the app STILL prompts me to subscribe every single time. I already paid. This is persistent, not a glitch.",
  customer: {
    ini: "MR",
    name: "Marcus Reeves",
    loc: "Seattle, WA · US-West",
    email: "marcus.reeves@gmail.com",
    phone: "+1 206-555-0142",
    veh: "2025 CR-V <b>Touring</b>",
    vin: "VIN 7FARW2H9•••0142 · plan <b class='ok'>ACTIVE</b>",
  },
  layer: "l3",
  rc: "ELIGIBILITY_RULE_CONFLICT",
  rb: "RB-ELIG-05",
  conf: 0.91,
  mttr: "3m 40s",
  steps: [
    {
      k: "Ingest",
      kk: "ticket + entitlement decision trace",
      v: "read the entitlement verdict for the VIN + 3 26GTC logs",
      ev: [
        "billing (Aria/SSP): plan=<span class='c'>Remote Connect (Touring)</span> · <span class='g'>ACTIVE</span> · paid 2026-06-30",
        "app entitlement verdict → <span class='r'>PROMPT_SUBSCRIBE ❌</span>  (conflict: already paid)",
      ],
    },
    {
      k: "Investigate",
      kk: "trace decision path + KB match",
      v: "follow the verdict path → find the override point",
      ev: [
        "eligibility_matrix[(<span class='c'>US-West</span>, <span class='c'>Touring</span>)] = <span class='a'>PROMPT_SUBSCRIBE</span>  ← added in release 26GTC-eli 07-08",
        "this static rule runs BEFORE the plan-active check → shadows the grant",
        "fingerprint match: <span class='g'>1,412 VINs</span> (region=US-West ∧ trim=Touring ∧ plan.active) · 2 past incidents",
      ],
    },
    {
      k: "Root cause",
      kk: "RB-ELIG-05",
      v: "<span class='hl'>ELIGIBILITY_RULE_CONFLICT</span> — precedence bug: a region-trim rule overrides an active plan",
    },
    {
      k: "Renovation (L3)",
      kk: "1 file · 1 unit test",
      v: "generate a <span class='cy'>patch</span> fixing the rule + a unit test reproducing the customer's case",
    },
  ],
  diff: [
    { t: "cmt", x: "  eligibility_matrix = {" },
    { t: "del", x: '-     ("US-West", "Touring"): PROMPT_SUBSCRIBE,   # override shadows the active plan' },
    { t: "add", x: '+     ("US-West", "Touring"): GRANT_IF_ACTIVE_PLAN,' },
    { t: "cmt", x: '      ("US-East", "Touring"): GRANT_IF_ACTIVE_PLAN,' },
    { t: "cmt", x: "  }" },
    { t: "cmt", x: "  # precedence: check plan-active BEFORE the static region-trim rule" },
  ],
  testName: "pytest ::test_touring_uswest_active_grants",
  reEval: "re-eval staging: 1,412/1,412 VINs → GRANT ✓",
};

const T4472: Omit<Ticket, "status"> = {
  id: "INC-4472",
  sev: "3",
  sys: "GTC · Entitlement Cache",
  impact: "~300 vehicles · flickering",
  title: "Entitlement works on web but drops in and out on the app after a cache node failover",
  complaint:
    "It works on the website but not in the app. It flickers on and off since this morning. Logging out helps for a minute then it's back.",
  customer: {
    ini: "PN",
    name: "Priya Nair",
    loc: "San Jose, CA · US-West",
    email: "priya.nair@gmail.com",
    phone: "+1 408-555-0177",
    veh: "2026 Accord <b>Touring</b>",
    vin: "VIN 1HGCY2F6•••8801 · plan <b class='ok'>ACTIVE</b>",
  },
  layer: "l2",
  rc: "ENTITLEMENT_CACHE_STALE",
  rb: "RB-CACHE-02",
  conf: 0.84,
  mttr: "2m 05s",
  steps: [
    {
      k: "Ingest",
      kk: "ticket + failover event 06:14",
      v: "compare the verdict from 2 sources: web (RTS) vs app (cache)",
      ev: [
        "web verdict (src=<span class='c'>RTS</span>): <span class='g'>GRANT ✓</span>  (fresh)",
        "app verdict (src=<span class='c'>cache-b2</span>): <span class='r'>NONE ❌</span>  (stale)",
      ],
    },
    {
      k: "Investigate",
      kk: "source diff + timeline",
      v: "cache-b2 not re-synced after the 06:14 failover → TTL not refreshed",
      ev: ["<span class='g'>300 VINs</span> stale · web≠app · no code-level fault"],
    },
    {
      k: "Root cause",
      kk: "RB-CACHE-02",
      v: "<span class='hl'>ENTITLEMENT_CACHE_STALE</span> — operational issue, NOT a code bug",
    },
    {
      k: "Remediation (L2)",
      kk: "self-executed · with rollback",
      v: "build <span class='cy'>invalidate + resync</span> from RTS per runbook, auto-run",
    },
  ],
  exec: [
    { t: "cmd", x: "$ gtc-cli entitlement invalidate --scope US-West --node cache-b2" },
    { t: "out", x: "  → 300 stale entries flushed" },
    { t: "cmd", x: "$ gtc-cli entitlement resync --source RTS --scope US-West" },
    { t: "out", x: "  → resync 300/300 OK (1.9s)" },
    { t: "ok", x: "verify: app == web on 20/20 sample VINs ✓  (incl. Priya's VIN)" },
    { t: "out", x: "rollback: snapshot cache-2026-07-09T06:20Z (ready)" },
  ],
};

const T4473: Omit<Ticket, "status"> = {
  id: "INC-4473",
  sev: "2",
  sys: "TCU · NGT",
  impact: "~40 vehicles · one parking garage",
  title: "A whole cluster of cars in a parking garage: remote commands time out, TCU no-signal",
  complaint:
    "None of the remote commands work when my car is parked in the office garage. It just times out every time.",
  customer: {
    ini: "DO",
    name: "Daniel Osei",
    loc: "Chicago, IL · US-East",
    email: "daniel.osei@gmail.com",
    phone: "+1 312-555-0195",
    veh: "2025 Pilot <b>Elite</b>",
    vin: "VIN 5FNYF8•••3320 · plan <b class='ok'>ACTIVE</b>",
  },
  layer: "route",
  rc: "TCU_OFFLINE",
  rb: "RB-TCU-04",
  conf: 0.88,
  mttr: "1m 30s",
  steps: [
    {
      k: "Ingest",
      kk: "ticket + TCU telemetry",
      v: "read the TCU state for the VIN cluster",
      ev: [
        "<span class='g'>40 VINs</span> at the same location 41.878,-87.629 · <span class='r'>RSSI=0</span> · last-seen 41m ago",
      ],
    },
    {
      k: "Investigate",
      kk: "no-signal / garage cue",
      v: "correlate cues → all lost signal, same place, same time",
      ev: ["no fault in Honda's software layer · pattern = lost cellular (concrete garage)"],
    },
    {
      k: "Root cause",
      kk: "RB-TCU-04",
      v: "<span class='hl'>TCU_OFFLINE</span> — environmental cause (cellular), not software",
    },
    {
      k: "Routing",
      kk: "no-code · comms",
      v: "route to the right team + send customer comms, do NOT fabricate a fix",
    },
  ],
  route: {
    rc: "TCU_OFFLINE — environmental (cellular / concrete garage)",
    to: "route: <b>Telematics / Carrier Ops</b> · send a guidance email to Daniel · alert auto-closes when signal returns",
    chips: [
      { t: "carrier ticket", ok: true },
      { t: "customer email", ok: true },
      { t: "auto-close on RSSI>0" },
    ],
  },
};

const T_PAY: Omit<Ticket, "status"> = {
  id: "INC-4474",
  sev: "3",
  sys: "SSP · HondaPay · Entitlement",
  impact: "1 order · just purchased",
  title: "Paid but the feature never switched on — activation event dropped",
  complaint:
    "I paid this morning and the feature still hasn't switched on. The charge went through but nothing activated.",
  customer: {
    ini: "EC",
    name: "Emily Carter",
    loc: "San Francisco, CA · US-West",
    email: "emily.carter@gmail.com",
    phone: "+1 415-555-0163",
    veh: "2026 Civic <b>Touring</b>",
    vin: "VIN 19XFL1•••7742 · charge <b class='ok'>CAPTURED</b>",
  },
  layer: "l2",
  rc: "PAYMENT_WEBHOOK_LOST",
  rb: "RB-PAY-01",
  conf: 0.82,
  mttr: "4m 30s",
  steps: [
    {
      k: "Ingest",
      kk: "order + payment status",
      v: "read the payment & entitlement state for the order",
      ev: [
        "HondaPay/Stripe: charge <span class='g'>CAPTURED ✓</span> (order ORD-8815)",
        "entitlement record: <span class='r'>MISSING ❌</span> → feature not switched on",
      ],
    },
    {
      k: "Investigate",
      kk: "RB-PAY-01 match",
      v: "trace the payment → entitlement pipeline",
      ev: ["activation event (payment→entitlement) = <span class='r'>DROPPED</span> · retry did not succeed"],
    },
    {
      k: "Root cause",
      kk: "RB-PAY-01",
      v: "<span class='hl'>PAYMENT_WEBHOOK_LOST</span> — payment captured but the entitlement-creation event did not complete",
    },
    {
      k: "Remediation (L2)",
      kk: "replay · idempotent",
      v: "<span class='cy'>replay the activation event</span>, re-create entitlement, verify",
    },
  ],
  exec: [
    { t: "cmd", x: "$ pay-cli event status --order ORD-8815" },
    { t: "out", x: "  → charge CAPTURED · entitlement MISSING · activation=DROPPED" },
    { t: "cmd", x: "$ pay-cli activation replay --order ORD-8815 --source HondaPay" },
    { t: "out", x: "  → entitlement created ✓ (propagated → GTC)" },
    { t: "ok", x: "verify: app shows the feature ✓ (Emily's VIN)" },
    { t: "out", x: "replay is idempotent — safe, no double charge" },
  ],
};

const T_TOKEN: Omit<Ticket, "status"> = {
  id: "INC-4475",
  sev: "2",
  sys: "HIDAS / IAM · CIAM",
  impact: "~90 accounts",
  title: "Subscription active but the feature returns 403; sign-out/in still blocked",
  complaint:
    "When I tap Remote Start the app says permission denied and logs me out. I've signed out and back in many times, still blocked, even though my plan is active.",
  customer: {
    ini: "RP",
    name: "Raj Patel",
    loc: "Dallas, TX · US-East",
    email: "raj.patel@gmail.com",
    phone: "+1 469-555-0188",
    veh: "2025 Accord <b>Sport</b>",
    vin: "VIN 1HGCV1•••5510 · plan <b class='ok'>ACTIVE</b>",
  },
  layer: "l3",
  rc: "TOKEN_SCOPE",
  rb: "RB-IAM-03",
  conf: 0.86,
  mttr: "5m 10s",
  steps: [
    {
      k: "Ingest",
      kk: "token claims + entitlement",
      v: "read the access-token scope + entitlement state",
      ev: [
        "entitlement: <span class='g'>ACTIVE ✓</span>",
        "token scope: missing <span class='r'>feature:remote ❌</span> → endpoint returns <span class='r'>403</span>",
      ],
    },
    {
      k: "Investigate",
      kk: "token refresh still missing",
      v: "re-auth but the scope is still absent → entitlement→scope mapping bug",
      ev: ["<span class='g'>90 accounts</span> have the 'remote' entitlement but the scope map omits it"],
    },
    {
      k: "Root cause",
      kk: "RB-IAM-03",
      v: "<span class='hl'>TOKEN_SCOPE</span> — entitlement→scope mapping wrong (not just a stale token) → needs a patch + reissue",
    },
    {
      k: "Renovation (L3)",
      kk: "1 file · 1 unit test",
      v: "generate a <span class='cy'>patch</span> adding the scope + reissue token, unit test to prevent regression",
    },
  ],
  diff: [
    { t: "cmt", x: "  entitlement_scope = {" },
    { t: "del", x: '-     "remote_connect": ["telemetry:read"],          # missing control scope' },
    { t: "add", x: '+     "remote_connect": ["telemetry:read", "feature:remote"],' },
    { t: "cmt", x: '      "digital_key":    ["feature:key"],' },
    { t: "cmt", x: "  }" },
  ],
  testName: "pytest ::test_remote_connect_grants_feature_scope",
  reEval: "reissue token for 90 accounts → 403 gone ✓",
};

const TEMPLATES = [T4471, T4472, T4473, T_PAY, T_TOKEN];

export function seedQueue(): Ticket[] {
  // No pre-seed — every ticket comes from L1 (via the real SLM), so all have an RCA.
  return [];
}

// --- L1 triage fallback: classify complaint → template (cue-based) ---
export interface TriageResult {
  layer: Layer;
  rc: string;
  rb: string;
  sev: "2" | "3";
  conf: number;
  cues: string[];
  templateIdx: number;
}

export function triage(complaint: string): TriageResult {
  const s = complaint.toLowerCase();
  const has = (arr: string[]) => arr.filter((w) => s.includes(w));

  const eligCues = has(["subscribe", "touring", "paid", "already pay", "prompt", "entitlement"]);
  const cacheCues = has(["website", "web", "app", "flicker", "logging out", "on and off", "cache"]);
  const tcuCues = has(["garage", "timeout", "times out", "signal", "no signal", "underground", "parked"]);

  const score = [
    { idx: 0, cues: eligCues },
    { idx: 1, cues: cacheCues },
    { idx: 2, cues: tcuCues },
  ].sort((a, b) => b.cues.length - a.cues.length)[0];

  const idx = score.cues.length ? score.idx : 0; // fallback ELIG
  const t = TEMPLATES[idx];
  return {
    layer: t.layer,
    rc: t.rc,
    rb: t.rb,
    sev: t.sev,
    conf: t.conf,
    cues: score.cues.length ? score.cues : ["(fuzzy match — most likely root cause)"],
    templateIdx: idx,
  };
}

// Samples = everyday situations (label does NOT reveal the root cause — the SLM classifies).
export const SAMPLES = [
  { label: "paid, app still asks to Subscribe", complaint: T4471.complaint, customer: T4471.customer },
  { label: "feature returns 403, re-login still blocked", complaint: T_TOKEN.complaint, customer: T_TOKEN.customer },
  { label: "works on web, app flickers", complaint: T4472.complaint, customer: T4472.customer },
  { label: "paid this morning, not activated", complaint: T_PAY.complaint, customer: T_PAY.customer },
  { label: "in the garage, remote times out", complaint: T4473.complaint, customer: T4473.customer },
];

export function ticketFromTemplate(idx: number, id: string, customer: Customer, complaint: string): Ticket {
  const t = TEMPLATES[idx];
  return { ...t, id, customer, complaint, status: "queued" };
}

// --- map root cause (returned by the SLM) → resolver template + layer ---
export const ABSTAIN_RC = "INSUFFICIENT_EVIDENCE";
export const RC_TO_IDX: Record<string, number> = {
  ELIGIBILITY_RULE_CONFLICT: 0,
  ENTITLEMENT_CACHE_STALE: 1,
  TCU_OFFLINE: 2,
  PAYMENT_WEBHOOK_LOST: 3,
  TOKEN_SCOPE: 4,
};
export function idxForRc(rc: string): number {
  return RC_TO_IDX[rc] ?? 0;
}
export function rcToLayer(rc: string): Layer {
  return TEMPLATES[idxForRc(rc)].layer;
}
export function sevForRc(rc: string): "2" | "3" {
  return TEMPLATES[idxForRc(rc)].sev;
}
export function defaultCustomer(rc: string): Customer {
  return TEMPLATES[idxForRc(rc)].customer;
}

const esc = (s: string) =>
  s.replace(/[&<>]/g, (c) => (({ "&": "&amp;", "<": "&lt;", ">": "&gt;" }) as Record<string, string>)[c]);

/** Build the L2/L3 ticket from the SLM result at L1.
 * - rc / conf / runbook: REAL from the SLM.
 * - RCA (evidence, why, fix_steps, owner…): REAL from the SLM → injected into the Investigate step + RCA card.
 * - Renovation (diff / exec / route): still from the template (mock) until #2-#4 are made real.
 * `d` is the NormalizedDiagnosis returned by /api/diagnose/slm. */
export function ticketFromSLM(id: string, customer: Customer, complaint: string, d: any): Ticket {
  const rc: string = d.rootCause || "ELIGIBILITY_RULE_CONFLICT";
  const conf: number = typeof d.confidence === "number" ? d.confidence : 0;
  const base = TEMPLATES[idxForRc(rc)];
  const evidence: string[] = Array.isArray(d.evidence) ? d.evidence : [];

  const steps: Step[] = base.steps.map((s) => ({ ...s, ev: s.ev ? [...s.ev] : undefined }));
  const handoff = `<span class='f'>L1 handoff · SLM:</span> ${rc} · conf ${conf.toFixed(2)}`;
  steps[0] = { ...steps[0], ev: [handoff, ...(steps[0].ev || [])] };
  // Investigate: replace the canned evidence with the REAL SLM evidence (cue-grounded quotes).
  if (evidence.length) {
    steps[1] = {
      ...steps[1],
      real: true,
      ev: evidence.map((e) => `<span class='g'>“</span>${esc(e)}<span class='g'>”</span>`),
    };
  }

  const slm: SlmRca = {
    evidence,
    summary: d.summary || "",
    nextActions: Array.isArray(d.nextActions) ? d.nextActions : [],
    owner: d.owner || null,
    escalation: d.escalation || null,
    affectedSystem: d.affectedSystem || null,
    similarIncident: d.similarIncident || null,
    missing: Array.isArray(d.missingEvidence) ? d.missingEvidence : [],
  };

  return { ...base, id, customer, complaint, rc, conf, rb: d.runbook || base.rb, steps, slm, status: "queued" };
}

export function layerBadge(layer: Layer): { label: string; cls: string } {
  if (layer === "l3") return { label: "L3 · code fix", cls: "l3" };
  if (layer === "l2") return { label: "L2 · auto-exec", cls: "l2" };
  return { label: "Route · no-code", cls: "route" };
}
