[program:honda-backend]
environment=PROC_NAME="%(program_name)s"
command=/opt/supervisor-scripts/honda-backend.sh
autostart=true
autorestart=unexpected
startsecs=5
stopasgroup=true
killasgroup=true
stopsignal=TERM
stopwaitsecs=10
# Bắt buộc để log ra Portal/Vast (phải là /dev/stdout)
stdout_logfile=/dev/stdout
redirect_stderr=true
stdout_events_enabled=true
stdout_logfile_maxbytes=0
stdout_logfile_backups=0
